version: '2.3'
services:
  wso2iot-mysql:
    image: mysql:5.7.20
    container_name: wso2iot-mysql
    hostname: wso2iot-mysql
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 10s
      timeout: 60s
      retries: 5
  wso2iot-broker:
    image: dockerhub.wso2.com/wso2iot-broker:3.1.0
    container_name: wso2iot-broker
    hostname: wso2iot-broker
    ports:
      - "9446:9446"
      - "5675:5675"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9446/carbon/admin/login.jsp"]
      interval: 10s
      timeout: 120s
      retries: 5
    depends_on:
      wso2iot-mysql:
        condition: service_healthy
    volumes:
      - ./broker/repository/conf/datasources/master-datasources.xml:/home/wso2carbon/wso2iot-3.1.0/wso2/broker/conf/datasources/master-datasources.xml
      - ./broker/repository/conf/broker.xml:/home/wso2carbon/wso2iot-3.1.0/wso2/broker/conf/broker.xml
      - ./broker/repository/conf/user-mgt.xml:/home/wso2carbon/wso2iot-3.1.0/wso2/broker/conf/user-mgt.xml
      - ./broker/repository/resources/security/client-truststore.jks:/home/wso2carbon/wso2iot-3.1.0/wso2/broker/repository/resources/security/client-truststore.jks
      - ./broker/repository/resources/security/wso2carbon.jks:/home/wso2carbon/wso2iot-3.1.0/wso2/broker/repository/resources/security/wso2carbon.jks
  wso2iot-analytics:
    image: dockerhub.wso2.com/wso2iot-analytics:3.1.0
    container_name: wso2iot-analytics
    hostname: wso2iot-analytics
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9445/carbon/admin/login.jsp"]
      interval: 10s
      timeout: 120s
      retries: 5
    volumes:
      - ./analytics/repository/conf/datasources/master-datasources.xml:/home/wso2carbon/wso2iot-3.1.0/wso2/analytics/conf/datasources/master-datasources.xml
      - ./analytics/repository/conf/datasources/analytics-datasources.xml:/home/wso2carbon/wso2iot-3.1.0/wso2/analytics/conf/datasources/analytics-datasources.xml
      - ./analytics/repository/conf/user-mgt.xml:/home/wso2carbon/wso2iot-3.1.0/wso2/analytics/repository/conf/user-mgt.xml
      - ./broker/repository/resources/security/client-truststore.jks:/home/wso2carbon/wso2iot-3.1.0/wso2/analytics/repository/resources/security/client-truststore.jks
      - ./broker/repository/resources/security/wso2carbon.jks:/home/wso2carbon/wso2iot-3.1.0/wso2/analytics/resources/security/wso2carbon.jks
    ports:
      - "9445:9445"
      - "9612:9612"
      - "9712:9712"
  wso2iot-server:
    image: dockerhub.wso2.com/wso2iot-server:3.1.0
    container_name: wso2iot-server
    hostname: wso2iot-server
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
      interval: 10s
      timeout: 120s
      retries: 5
    depends_on:
      wso2iot-analytics:
        condition: service_healthy
    volumes:
      - ./iot-server/repository/conf/datasources/master-datasources.xml:/home/wso2carbon/wso2iot-3.1.0/conf/datasources/master-datasources.xml
      - ./iot-server/repository/conf/api-manager.xml:/home/wso2carbon/wso2iot-3.1.0/conf/api-manager.xml
      - ./iot-server/repository/conf/app-manager.xml:/home/wso2carbon/wso2iot-3.1.0/conf/app-manager.xml
      - ./iot-server/repository/conf/carbon.xml:/home/wso2carbon/wso2iot-3.1.0/conf/carbon.xml
      - ./iot-server/repository/conf/iot-api-config.xml:/home/wso2carbon/wso2iot-3.1.0/conf/iot-api-config.xml
      - ./iot-server/repository/conf/user-mgt.xml:/home/wso2carbon/wso2iot-3.1.0/conf/user-mgt.xml
      - ./iot-server/repository/conf/etc/webapp-publisher-config.xml:/home/wso2carbon/wso2iot-3.1.0/conf/etc/webapp-publisher-config.xml
      - ./iot-server/repository/conf/identity/sso-idp-config.xml:/home/wso2carbon/wso2iot-3.1.0/conf/identity/sso-idp-config.xml
      - ./iot-server/repository/conf/identity/identity-providers/iot_default.xml:/home/wso2carbon/wso2iot-3.1.0/conf/identity/identity-providers/iot_default.xml
      - ./iot-server/repository/deployment/server/jaggeryapps/api-store/site/conf/site.json:/home/wso2carbon/wso2iot-3.1.0/repository/deployment/server/jaggeryapps/api-store/site/conf/site.json
      - ./iot-server/repository/deployment/server/jaggeryapps/devicemgt/app/conf/app-conf.json:/home/wso2carbon/wso2iot-3.1.0/repository/deployment/server/jaggeryapps/devicemgt/app/conf/app-conf.json
      - ./iot-server/repository/deployment/server/jaggeryapps/portal/configs/designer.json:/home/wso2carbon/wso2iot-3.1.0/repository/deployment/server/jaggeryapps/portal/configs/designer.json
      - ./iot-server/repository/resources/security/client-truststore.jks:/home/wso2carbon/wso2iot-3.1.0/repository/resources/security/client-truststore.jks
      - ./iot-server/repository/resources/security/wso2carbon.jks:/home/wso2carbon/wso2iot-3.1.0/repository/resources/security/wso2carbon.jks
      - ./iot-server/repository/resources/security/wso2certs.jks:/home/wso2carbon/wso2iot-3.1.0/repository/resources/security/wso2certs.jks
      - ./iot-server/bin/iot-server.sh:/home/wso2carbon/wso2iot-3.1.0/bin/iot-server.sh
    ports:
      - "9443:9443"
